### ISSUE TITLE
Is there a Markdown/HTML version of this tute?

### ISSUE THREAD

**Issue by tseemann** [soedinglab/metaG-ECCB18-partII#2]
(I have trouble reading PDFs)

**Comment by milot-mirdita** [comment]
I converted the tutorial and moved it to the MMseqs2 wiki:
https://github.com/soedinglab/MMseqs2/wiki/Tutorial-Advanced

For the workshop we had setup a cloud editor with all software and databases inside. I'll document all that in the next few days.

I'll also upload a beginner level tutorial that we developed for biology students sometime soon.

**Comment by tseemann** [comment]
Ah i was wondering if this was legacy - thank you!

**Comment by milot-mirdita** [comment]
I also added the more beginner friendly tutorial (and renamed the page to here https://github.com/soedinglab/MMseqs2/wiki/Tutorials).

We will keep adding stuff to this page and expanding the tutorials. Thanks again for reminding me to place this resource in some structured way somewhere.
